# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6ace764e1521a6d126490f8dcdfd74c2"
name = "Field Sales Manager"
application_url = "https://field-sales-admin.dualsidedapp.com"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/companies"
  topics = [ "companies/create", "companies/delete", "companies/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/company-locations"
  topics = [
  "company_locations/update",
  "company_locations/create",
  "company_locations/delete"
]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_companies,read_customer_payment_methods,read_customers,read_files,read_orders,read_products,write_companies,write_draft_orders,write_files,write_orders,write_payment_mandate"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://field-sales-admin.dualsidedapp.com/api/auth" ]
