# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f9fd79decc414b88daa949015eab027a"
name = "Field Sales Manager DEV"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "companies/create", "companies/delete", "companies/update" ]
  uri = "/webhooks/companies"

  [[webhooks.subscriptions]]
  topics = [
  "company_locations/create",
  "company_locations/delete",
  "company_locations/update"
]
  uri = "/webhooks/company-locations"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_companies,read_customers,read_orders,write_companies,write_draft_orders,write_orders,write_payment_mandate"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
